# Generated by Django 4.2.7 on 2023-11-27 17:18

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField()),
                ('updated_at', models.DateField()),
                ('file_name', models.CharField(max_length=300, verbose_name='Fayl nomi:')),
                ('file_type', models.FileField(upload_to='audio/', validators=[category.models.validate_file], verbose_name='Faylni tanlang')),
                ('size', models.CharField(max_length=200, verbose_name='fayl razmeri:')),
            ],
            options={
                'verbose_name': 'Fayl bolimi_',
            },
        ),
    ]
